-- AlterTable
ALTER TABLE "Workspace" ALTER COLUMN "adminCode" DROP DEFAULT,
ALTER COLUMN "canEditCode" DROP DEFAULT,
ALTER COLUMN "inviteCode" DROP DEFAULT,
ALTER COLUMN "readOnlyCode" DROP DEFAULT;
